//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resume_creator_api.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateDetail
    {
        public int ID { get; set; }
        public int LoginID { get; set; }
        public string Title { get; set; }
        public string Institute { get; set; }
        public int FromYear { get; set; }
        public Nullable<int> ToYear { get; set; }
        public bool HasNoExpiry { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual LoginProfile LoginProfile { get; set; }
    }
}
