//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resume_creator_api.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public int ID { get; set; }
        public int LoginID { get; set; }
        public string Client { get; set; }
        public string ProjectTitle { get; set; }
        public int FromMonth { get; set; }
        public int FromYear { get; set; }
        public Nullable<int> ToMonth { get; set; }
        public Nullable<int> ToYear { get; set; }
        public bool IsCurrent { get; set; }
        public string ProjectLocation { get; set; }
        public bool IsOnsite { get; set; }
        public int EmploymentType { get; set; }
        public string ProjectDetails { get; set; }
        public int Role { get; set; }
        public string RoleDescription { get; set; }
        public int TeamSize { get; set; }
        public string SkillsUsed { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual LoginProfile LoginProfile { get; set; }
    }
}
