//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resume_creator_api.edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeCreatorEntities : DbContext
    {
        public ResumeCreatorEntities()
            : base("name=ResumeCreatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CertificateDetail> CertificateDetails { get; set; }
        public virtual DbSet<EducationDetail> EducationDetails { get; set; }
        public virtual DbSet<EmployerHistory> EmployerHistories { get; set; }
        public virtual DbSet<LoginProfile> LoginProfiles { get; set; }
        public virtual DbSet<MasterDetail> MasterDetails { get; set; }
        public virtual DbSet<ProjectDetail> ProjectDetails { get; set; }
        public virtual DbSet<SummarySkill> SummarySkills { get; set; }
        public virtual DbSet<TechnicalSkill> TechnicalSkills { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }

        public System.Data.Entity.DbSet<resume_creator_api.ViewModels.UserProfileVM> UserProfileVMs { get; set; }
    }
}
